content:
  - id: homepage
    type: file
    path: index.md
    name: Home
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Page Content
        type: rich-text
