media:
  input: assets
  output: /assets

content:
  - type: file
    path: index.md
    name: Home Page
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text